import { chromium } from 'playwright';
const b = await chromium.connectOverCDP('http://127.0.0.1:9224');
const ctx = b.contexts()[0];
const p = await ctx.newPage();
await p.goto('https://www.instagram.com/direct/inbox/', { waitUntil:'domcontentloaded', timeout:60000 });
await p.waitForTimeout(6000);
const t = (await p.locator('body').innerText()).replace(/\n{2,}/g,'\n');
console.log('URL:', p.url());
console.log('logged in:', !p.url().includes('/accounts/login'));
console.log('--- first 900 chars ---');
console.log(t.slice(0,900));
await p.close(); await b.close();
